# -*- coding: utf-8 -*-
"""Biodata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u7sFGkwiz2vq-0PoumjaTv-hk6_orXup
"""

name = input("Enter your name: ")
age = input("Enter your age: ")
course = input("Enter your course: ")

print("----- BIODATA -----")
print("Name:", name)
print("Age:", age)
print("Course:", course)